version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.15.3
  aws-ecs: circleci/aws-ecs@2.1.0
jobs:
  build_and_test:
    docker:
      - image: cimg/ruby:3.2.4
        environment:
          RAILS_ENV: test
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Set up database
          command: |
            bundle exec rails db:create
            bundle exec rails db:schema:load
      - run:
          name: Run tests
          command: bundle exec rails test
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_and_test
      - aws-ecr/build-and-push-image:
          requires:
            - build_and_test
          account-url: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
          repo: '${AWS_RESOURCE_NAME_PREFIX}'
          region: ${AWS_REGION}
          tag: '${CIRCLE_SHA1}'
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: '${AWS_RESOURCE_NAME_PREFIX}-service'
          cluster-name: '${AWS_RESOURCE_NAME_PREFIX}-cluster'
          container-image-name-updates: '${AWS_RESOURCE_NAME_PREFIX}-service=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_RESOURCE_NAME_PREFIX}:${CIRCLE_SHA1}'